_name: null
common:
  _name: null
  no_progress_bar: false
  log_interval: 10
  log_format: csv
  log_file: null
  wandb_project: null
  wandb_entity: null
  seed: 1
  fp16: false
  memory_efficient_fp16: false
  fp16_no_flatten_grads: false
  fp16_init_scale: 128
  fp16_scale_window: null
  fp16_scale_tolerance: 0.0
  on_cpu_convert_precision: false
  min_loss_scale: 0.0001
  threshold_loss_scale: null
  empty_cache_freq: 0
  all_gather_list_size: 2048000
  model_parallel_size: 1
  profile: false
  reset_logging: false
  suppress_crashes: false
common_eval:
  _name: null
  path: null
  quiet: false
  model_overrides: '{}'
  save_outputs: false
  results_path: null
distributed_training:
  _name: null
  distributed_world_size: 4
  distributed_rank: 0
  distributed_backend: nccl
  distributed_init_method: null
  distributed_port: 12355
  device_id: 0
  ddp_comm_hook: none
  bucket_cap_mb: 25
  fix_batches_to_gpus: false
  find_unused_parameters: true
  heartbeat_timeout: -1
  broadcast_buffers: false
  fp16: ${common.fp16}
  memory_efficient_fp16: ${common.memory_efficient_fp16}
dataset:
  _name: null
  num_workers: 3
  skip_invalid_size_inputs_valid_test: false
  max_tokens: null
  batch_size: 64
  required_batch_size_multiple: 8
  data_buffer_size: 10
  train_subset: train
  valid_subset: valid
  combine_valid_subsets: null
  ignore_unused_valid_subsets: false
  validate_interval: 1
  validate_interval_updates: 0
  validate_after_updates: 0
  fixed_validation_seed: null
  disable_validation: false
  max_tokens_valid: ${dataset.max_tokens}
  batch_size_valid: ${dataset.batch_size}
  max_valid_steps: null
  curriculum: 0
  num_shards: 1
  shard_id: 0
optimization:
  _name: null
  max_epoch: 50
  max_update: 320000
  lr:
  - 1.0e-06
  stop_time_hours: 0.0
  clip_norm: 0.0
  update_freq:
  - 1
  stop_min_lr: -1.0
checkpoint:
  _name: null
  save_dir: <REDACTED>
  restore_file: checkpoint_last.pt
  finetune_from_model: null
  reset_dataloader: false
  reset_lr_scheduler: false
  reset_meters: false
  reset_optimizer: false
  optimizer_overrides: '{}'
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: -1
  keep_interval_updates_pattern: -1
  keep_last_epochs: 0
  keep_best_checkpoints: -1
  no_save: false
  no_epoch_checkpoints: false
  no_last_checkpoints: false
  no_save_optimizer_state: false
  best_checkpoint_metric: loss
  maximize_best_checkpoint_metric: false
  patience: -1
  checkpoint_suffix: ''
  checkpoint_shard_count: 1
  load_checkpoint_on_all_dp_ranks: false
model:
  _name: ecg_transformer_classifier
  model_path: <REDACTED>
  num_labels: 26
  no_pretrained_weights: false
  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  in_d: 12
task:
  _name: ecg_classification
  data: <REDACTED>
  normalize: false
  enable_padding: true
  enable_padding_leads: false
  leads_to_load: null
  label_file: null
criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  report_cinc_score: false
  weights_file: ???
  pos_weight:
  - 15.390331
  - 9.366471
  - 178.694517
  - 307.623318
  - 58.330172
  - 16.724182
  - 23.509615
  - 45.128016
  - 10.223581
  - 38.081772
  - 223.179153
  - 53.063629
  - 43.894325
  - 48.763557
  - 1.994518
  - 25.936595
  - 58.587013
  - 143.283019
  - 44.729568
  - 40.310324
  - 68.729483
  - 23.999274
  - 3.564768
  - 8.647183
  - 6.384442
  - 20.731291
lr_scheduler:
  _name: fixed
  warmup_updates: 0
optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1.0e-08
